"""
Service interfaces module.

This module defines abstract interfaces (Protocols) for services used in PII
detection, sensitive topic detection, external LLM processing, and text restoration.
These interfaces allow dependency injection and ensure low coupling for
implementation classes.
"""

from typing import Protocol, List, Any, Tuple
from abc import abstractmethod

from src.models.models import PIIMapping


class IRegexService(Protocol):
    """
    Interface for regex-based PII detection and filtering service.
    """

    @abstractmethod
    def filter_by_regex(
        self, text: str, validate_pii_data: bool = False
    ) -> Tuple[str, List[PIIMapping]]:
        """
        Filters the input text using regex patterns to detect PII.

        Args:
            text (str): The text to analyze.
            validate_pii_data (bool, optional): Whether to validate the PII data. Defaults to False.

        Returns:
            Tuple[str, List[PIIMapping]]: A tuple containing the filtered text and a list of detected PII mappings.
        """


class ISensitiveTopicDetector(Protocol):
    """
    Interface for detecting sensitive topics using local models.
    """

    @abstractmethod
    def filter_sensitive_topics(
        self, text: str, existing_placeholders: List[str] = None
    ) -> Tuple[str, List[PIIMapping]]:
        """
        Detects sensitive topics in the text.

        Args:
            text (str): The text to analyze.

        Returns:
            Tuple[str, List[PIIMapping]]: A tuple containing the filtered text and a list of detected sensitive topic mappings.
        """


class IExternalLLM(Protocol):
    """
    Interface for external Large Language Model (LLM) service.
    """

    @abstractmethod
    def send_prompt(self, prompt: str) -> str:
        """
        Sends a prompt to the external LLM and returns the response.

        Args:
            prompt (str): The input prompt text.

        Returns:
            str: The text response from the LLM.
        """


class IRestorationService(Protocol):
    """
    Interface for restoring PII placeholders in processed text.
    """

    @abstractmethod
    def create_restoration_data(
        self, regex_mappings: List[PIIMapping], llm_mappings: List[PIIMapping]
    ) -> Any:
        """
        Creates the data structure needed to restore masked PII placeholders.

        Args:
            regex_mappings (List[PIIMapping]): List of PII mappings detected by regex.
            llm_mappings (List[PIIMapping]): List of PII/sensitive topic mappings detected by LLM.

        Returns:
            Any: The restoration data to be used for restoring the text.
        """

    @abstractmethod
    def restore_all(self, text: str, restoration_data: Any) -> str:
        """
        Restores all PII placeholders in the text using the provided restoration data.

        Args:
            text (str): Text containing masked PII placeholders.
            restoration_data (Any): Data generated by create_restoration_data.

        Returns:
            str: The text with original PII restored.
        """


class INERService(Protocol):
    """
    Interface for NER-based PII detection and filtering service.
    """

    @abstractmethod
    def filter_by_ner(
        self,
        text: str,
        existing_placeholders: List[str] = None,
    ) -> Tuple[str, List[PIIMapping]]:
        """
        Filters the input text using NER models to detect PII.

        Args:
            text (str): The text to analyze.
            existing_placeholders (List[str], optional): A list of placeholders
                from previous steps to avoid re-processing.

        Returns:
            Tuple[str, List[PIIMapping]]: A tuple containing the filtered text
                and a list of detected PII mappings.
        """
